# Generated by Django 4.2.6 on 2024-06-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitycode',
            index=models.Index(fields=['email'], name='user_activity_email_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitycode',
            index=models.Index(fields=['activation_code'], name='activation_code_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='user_role_idx'),
        ),
    ]
