# Generated by Django 4.2.6 on 2024-06-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrole',
            name='user_role_idx',
        ),
    ]
