# Generated by Django 4.2.6 on 2024-06-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookcategory',
            name='book_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_book_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_user_book_idx',
        ),
        migrations.RemoveIndex(
            model_name='userbook',
            name='user_book_idx',
        ),
        migrations.RemoveIndex(
            model_name='userbookmark',
            name='user_bookmark_book_user_idx',
        ),
    ]
