# Generated by Django 4.2.6 on 2024-06-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publisher'], name='publisher_book_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name'], name='name_book_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author_name'], name='author_name_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcategory',
            index=models.Index(fields=['book', 'category'], name='book_category_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['book', 'user'], name='comment_book_user_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'book'], name='review_user_book_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'book'], name='user_book_idx'),
        ),
        migrations.AddIndex(
            model_name='userbookmark',
            index=models.Index(fields=['user', 'book'], name='user_bookmark_book_user_idx'),
        ),
    ]
