# Generated by Django 4.2.6 on 2024-06-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('quantity', models.IntegerField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_discounts',
            },
        ),
        migrations.CreateModel(
            name='WalletActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'wallet_action_types',
            },
        ),
        migrations.CreateModel(
            name='WalletAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_successful', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walletactiontype')),
            ],
            options={
                'db_table': 'wallet_actions',
            },
        ),
    ]
