# Generated by Django 4.2.6 on 2024-06-07 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userdiscount',
            name='user_discount_idx',
        ),
        migrations.AlterField(
            model_name='walletaction',
            name='action_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.walletactiontype'),
        ),
        migrations.AlterField(
            model_name='walletaction',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
